---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elastic-operator
  namespace: default
  annotations:
    kyverno.io/disallow-missing-finalizer: "ignore"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: elastic-system
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true
  source:
    repoURL: https://github.com/elastic/cloud-on-k8s.git
    path: deploy/eck-operator
    targetRevision: v2.12.1
    helm:
      values: |
        resources:
          limits:
            cpu: 1
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 150Mi
        podAnnotations: {}
