elasticsearch:
  enabled: true
  name: product42
  count: 1
  version: 8.13.2
  resources:
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 0.5
      memory: 1Gi


kibana:
  enabled: true
  name: product42
  count: 1
  version: 8.13.2
  resources:
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 0.5
      memory: 1Gi

filebeat:
  enabled: false
  name: filebeat
  version: 8.13.2

logstash:
  enabled: false
  count: 1
  name: logstash
