{{- if .Values.kibana.enabled }}
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: {{ .Values.kibana.name }}
spec:
  version: {{ .Values.kibana.version }}
  count: {{ .Values.kibana.count }}
  elasticsearchRef:
    name: {{ .Values.elasticsearch.name }}
  podTemplate:
    spec:
      containers:
        - name: kibana
          resources:
{{ toYaml .Values.kibana.resources | indent 12 }}
{{ end }}
